theme:
  name: material
  favicon: favicon.ico
  logo: images/archer2_white_transparent.png
  palette:
    primary: custom
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/archer2.css

site_name: ARCHER2 User Documentation
repo_url: https://github.com/ARCHER2-HPC/archer2-docs
repo_name: ARCHER2-HPC/archer2-docs
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARCHER2-HPC
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ARCHER2_HPC
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/13848871/
  analytics:
    provider: google
    property: UA-165933823-2
  analytics:
    provider: google
    property: G-XVNML97F1T

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  


  

nav:
  - "Documentation overview": index.md
  - "Quickstart":
    - "Overview": quick-start/overview.md
    - "Quickstart for users": quick-start/quickstart-users.md
    - "Quickstart for developers": quick-start/quickstart-developers.md
    - "Quickstart next steps": quick-start/quickstart-next-steps.md
  - "ARCHER2 Known Issues": known-issues/index.md
  - "ARCHER2 Frequently Asked Questions":
    - "General FAQ": faq/index.md
  - "User and Best Practice Guide":
    - "Overview": user-guide/index.md
    - "Hardware": user-guide/hardware.md
    - "Connecting to ARCHER2": user-guide/connecting.md
    - "Data management and transfer": user-guide/data.md
    - "Software environment": user-guide/sw-environment.md
    - "Running jobs": user-guide/scheduler.md
    - "I/O and file systems": user-guide/io.md
    - "Application development environment": user-guide/dev-environment.md
    - "Containers": user-guide/containers.md
    - "Using Python": user-guide/python.md
    - "Machine Learning": user-guide/machine-learning.md
    - "Data analysis": user-guide/analysis.md
    - "Debugging": user-guide/debug.md
    - "Profiling": user-guide/profile.md
    - "Performance tuning": user-guide/tuning.md
    - "Energy use": user-guide/energy.md
    - "GPU development platform": user-guide/gpu.md
    - "Functional accounts": user-guide/functional-accounts.md
  - "Research Software":
    - "Overview": research-software/index.md
    - "CASINO": research-software/casino.md
    - "CASTEP": research-software/castep.md
    - "CESM2": research-software/cesm.md
    - "Chemshell": research-software/chemshell.md
    - "Code_Saturne": research-software/code-saturne.md
    - "CP2K": research-software/cp2k.md
    - "CRYSTAL": research-software/crystal.md
    - "FHI-aims": research-software/fhi-aims.md
    - "GROMACS": research-software/gromacs.md
    - "LAMMPS": research-software/lammps.md
    - "MITgcm": research-software/mitgcm.md
    - "Met Office Unified Model": research-software/mo-unified-model.md
    - "NAMD": research-software/namd.md
    - "Nektar++": research-software/nektarplusplus.md
    - "NEMO": research-software/nemo.md
    - "NWChem": research-software/nwchem.md
    - "ONETEP": research-software/onetep.md
    - "OpenFOAM": research-software/openfoam.md
    - "ORCA": research-software/orca.md
    - "QChem": research-software/qchem.md
    - "Quantum Espresso": research-software/qe.md
    - "VASP": research-software/vasp.md
  - "Software Libraries":
    - "Overview": software-libraries/index.md
    - "HPE Cray LibSci: BLAS, LAPACK, ScaLAPACK": software-libraries/libsci.md
    - "FFTW": software-libraries/fftw.md
    - "HDF5": software-libraries/hdf5.md
    - "NetCDF": software-libraries/netcdf.md
    - "AOCL": software-libraries/aocl.md
    - "ARPACK": software-libraries/arpack.md
    - "Boost": software-libraries/boost.md
    - "Eigen": software-libraries/eigen.md
    - "GLM":   software-libraries/glm.md
    - "HYPRE": software-libraries/hypre.md
    - "Matio": software-libraries/matio.md
    - "Intel MKL": software-libraries/mkl.md
    - "MESA": software-libraries/mesa.md
    - "MUMPS": software-libraries/mumps.md
    - "PETSc": software-libraries/petsc.md
    - "Metis/Parmetis": software-libraries/metis.md
    - "Scotch/PT-Scotch": software-libraries/scotch.md
    - "SLEPc" : software-libraries/slepc.md
    - "SuperLU/SuperLU_DIST": software-libraries/superlu.md
    - "Trilinos": software-libraries/trilinos.md
  - "Data Analysis and Tools":
    - "Overview": data-tools/index.md
    - "AMD uProf": data-tools/amd-uprof.md
    - "Linaro Forge": data-tools/forge.md
    - "Darshan": data-tools/darshan.md
    - "Energy Counters": data-tools/pm-mpi-lib.md
    - "Globus": data-tools/globus.md
    - "Julia": data-tools/julia.md
    - "ParaView": data-tools/paraview.md
    - "R": data-tools/cray-r.md
    - "Spack": data-tools/spack.md
    - "VisiData": data-tools/visidata.md
    - "VMD": data-tools/vmd.md
  - "Essential Skills": essentials/index.md
  - "ARCHER2 and Publications": publish/index.md
